version: '3.8'

services:
  ansible:
    tty: true
    build:
      no_cache: true
      context: ./ansible
      dockerfile: Dockerfile
    volumes:
      - ./ansible:/ansible
      - ./certs:/root/.ssh
    command: tail -f /dev/null

  k3s:
    tty: true
    build:
      context: ./k8s/k3sup
      dockerfile: Dockerfile
    volumes:
      - ./k3s:/home/ubuntu/k3s
      - ./certs:/home/ubuntu/.ssh
    command: tail -f /dev/null
