# This is the network config written by 'subiquity'
network:
  version: 2
  ethernets:
    ens33:
      dhcp4: yes
#      addresses:
#        - 192.168.41.129/24
#      gateway4: 192.168.41.254
#      nameservers:
#        addresses: [8.8.8.8, 1.1.1.1]
