---
- hosts: proxmox
  become: true
  remote_user: root
  vars_files:
    - vars.yml

  tasks:
    - name: Install deps
      apt:
        name: {{ packages }}
        state: present
        update_cache: yes
      vars:
        packages:
          - libguestfs-tools

    - name: Download image
      ansible.builtin.get_url:
        url: {{ image.url }}
        dest: {{ image.dest }}
        mode: 0644

    - name: Stop old vm
      ansible.builtin.command: qm stop {{ vm.id }}
      ignore_errors: yes

    - name: Remove old template
      ansible.builtin.command: qm destroy {{ vm.id }}
      ignore_errors: yes

    - name: Customize image (install packages)
      ansible.builtin.command: virt-customize -a {{ image.dest }} --install qemu-guest-agent

    - name: Customize image (set root passwd)
      ansible.builtin.command: virt-customize -a {{ image.dest }} --root-password password:{{ vm.rootPassword }}

    - name: Create VM
      ansible.builtin.command: |
        qm create {{ vm.id }} 
        --name {{ template.name }} 
        --cores {{ vm.cores }} 
        --memory {{ vm.memory }} 
        --net0 virtio,bridge={{ vm.network }}

    - name: Import disk
      ansible.builtin.command: qm importdisk {{ vm.id }} {{ image.dest }} {{ vm.volumeName }}

    - name: Set VM disk
      ansible.builtin.command: qm set {{ vm.id }} --scsihw virtio-scsi-pci --scsi0 {{ vm.volumeName }}:vm-{{ vm.id }}-disk-0

    - name: Set VM boot disk
      ansible.builtin.command: qm set {{ vm.id }} --boot c --bootdisk scsi0

    - name: Set VM attach cloudinit
      ansible.builtin.command: qm set {{ vm.id }} --ide2 {{ vm.volumeName }}:cloudinit

    - name: Set VM serial
      ansible.builtin.command: qm set {{ vm.id }} --serial0 socket --vga serial0

    - name: Set VM ip opts
      ansible.builtin.command: qm set {{ vm.id }} --ipconfig0 ip={{ vm.ip }}

    - name: Set VM cpu type
      ansible.builtin.command: qm set {{ vm.id }} --cpu cputype={{ vm.cpuType }}

    - name: Create template
      ansible.builtin.command: qm template {{ vm.id }}
