- name: Create VMs
  tags: proxmox, create, deploy
  proxmox:
    vmid: '{{ item.value.vmid | default([])}}'
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host: "{{ api_host }}"
    hostname: '{{ item.key }}'
    node: '{{ item.value.node | default(defaults.node) }}'
    password: '{{ item.value.password }}'
    pubkey: '{{ item.value.pubkey | default(defaults.pubkey) }}'
    cores: '{{ item.value.cores | default(defaults.cores) }}'
    cpus: '{{ item.value.cpu | default(defaults.cpu) }}'
    memory: '{{ item.value.memory | default(defaults.memory.ct) }}'
    swap: '{{ item.value.swap | default([]) }}'
    disk: '{{ item.value.disk | default(defaults.disk) }}'
    #mounts: '{{ item.value.mounts | default([]) }}'
    netif: '{{ item.value.netif | default([]) }}'
    storage: '{{ item.value.storage | default(defaults.storage.ct) }}'
    onboot: '{{ item.value.onboot | default(defaults.onboot) }}'
    nameserver: '{{ item.value.nameserver | default(defaults.nameserver) }}'
    ostemplate: '{{ item.value.ostemplate | default(defaults.ostemplate) }}'
    state: 'present'
  with_dict: "{{ cts }}"
  loop_control:
    pause: 5
  notify:
    - sleep
  register: 'created_cts_pve'
  when: 'not item.value.cloudinit | default(false) | bool'

- meta: flush_handlers
