defaults:
  cores: '1'
  cpu: '1'
  memory:
    ct: '1024'
  onboot: true
  node: 'pve'
  password: 'admin'
  pubkey: "{{ lookup('file', '/home/.ssh/id_rsa.pub') }}"
  nameserver: '192.168.1.1'
  storage:
    ct: 'local-lvm'
  disk:
    size: '10G'
  template:
    id: '9000'
  ipconfig0: 'ip=dhcp'
  net0: 'virtio,bridge=vmbr0'
  #ipconfig0: 'ip=192.168.1.10/24,gw=192.168.1.1' # for static

template:
  id: "9000"
  name: "ubuntu-server-template"
  user: "ubuntu"
  password: "admin" # "{{ vault_template_password }}"
  cores: "4"
  memory: "4096"
  volumeName: "local-lvm"
  network: "vmbr0"
  rootPassword: "admin" # "{{ vault_template_rootPassword }}"
  sshPubKey: "{{ lookup('file', '/home/.ssh/id_rsa.pub') }}"
  cpuType: "host"
  ip: "dhcp"
  custom: "network=local:snippets/network-config.yaml"
  image:
    url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
    name: "jammy-server-cloudimg-amd64.img"
    dest: "/var/lib/vz/template/iso/jammy-server-cloudimg-amd64.img"

vms:
  - id: '101'
    onboot: true
    name: 'master-node'
    type: 'ubuntu'
    cores: '4'
    memory:
      ct: '4096'
    swap: '0'
    # ipconfig0: 'ip=192.168.1.12/24,gw=192.168.1.1'
    # net0: 'virtio,bridge=vmbr0'
    password: 'admin' # "{{ vault_101 }}"
  - id: '102'
    onboot: true
    name: 'worker-node'
    type: 'ubuntu'
    cores: '4'
    memory:
      ct: '4096'
    swap: '0'
    # ipconfig0: 'ip=192.168.1.13/24,gw=192.168.1.1'
    # net0: 'virtio,bridge=vmbr0'
    password: 'admin' # "{{ vault_102 }}"
