{{- range $application := .Values.applications }}
{{- range $namespace := $application.namespaces }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $namespace }}-{{ $application.name }}
  namespace: {{ .Values.namespace }} # Apply argocd apps to default namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io # see. ...
  {{- with $application.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  destination:
    namespace: {{ $namespace }}
    server: https://kubernetes.default.svc
  project: {{ .Values.projectName }} # you can use your own naming here
  source:
    path: {{ .Values.repoPath }}
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.repoBranch }}
    helm:
      valueFiles:
        - values.yaml
        - values/{{ $application.name }}.yaml
        - values/{{ $namespace }}/{{ $application.name }}.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
{{- end }}
{{- end }}
