---
namespaces: ['argocd', 'infra', 'monitoring']

# TODO add kube-prometheus-stack

applications:
  - name: cert-manager # ingress
    enabled: false
    namespace: infra
    chart: cert-manager
    targetRevision: v1.8.0
    repoURL: https://charts.jetstack.io
  - name: mongodb # db
    enabled: false
    namespace: infra
    chart: mongodb
    targetRevision: 13.6.6
    repoURL: https://charts.bitnami.com/bitnami
  - name: rabbitmq # message-broker
    enabled: false
    namespace: infra
    chart: rabbitmq
    targetRevision: 11.6.0
    repoURL: https://charts.bitnami.com/bitnami
